Repository AY2324S1-CS2113-W12-3/tp, pull requests merged in 2023-10, with the labels that each got.

#24 Add JUnit tests for Parser class
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Task, priority.High

#11 Add help command feature
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.Medium

#26 Add JUnit test for HelpCommand Class
  src/main/java/seedu/duke/command/HelpCommand.java
  src/test/java/seedu/duke/help/HelpCommandTest.java
Labels: type.Task, priority.High

#40 Enable assertion on gradle
  build.gradle
Labels: priority.High

#43 Added adding/removing of Goal and Category and relevant tests
  src/main/java/seedu/duke/classes/Goal.java
  src/main/java/seedu/duke/classes/StateManager.java
  src/main/java/seedu/duke/command/AddExpenseCommand.java
  src/main/java/seedu/duke/command/AddIncomeCommand.java
  src/main/java/seedu/duke/command/CategoryCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/CategoryCommandTest.java
  src/test/java/seedu/duke/command/GoalCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveTransactionCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Story, priority.High

#52 Modify parser to return empty string instead of null when user never …
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: task.Bug

#54 Add Developer Guide for Parser class
  docs/DeveloperGuide.md
Labels: type.Task

#55 Add Developer Guide for Command component
  docs/DeveloperGuide.md
Labels: type.Task

#51 Recurring transactions
  src/main/java/seedu/duke/classes/Expense.java
  src/main/java/seedu/duke/classes/Income.java
  src/main/java/seedu/duke/classes/StateManager.java
  src/main/java/seedu/duke/classes/Transaction.java
  src/main/java/seedu/duke/classes/TransactionRecurrence.java
  src/main/java/seedu/duke/command/AddExpenseCommand.java
  src/main/java/seedu/duke/command/AddIncomeCommand.java
  src/main/java/seedu/duke/command/AddTransactionCommand.java
  src/main/java/seedu/duke/command/CategoryCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/CommandTestCase.java
  src/test/java/seedu/duke/command/CommandTestUtils.java
  src/test/java/seedu/duke/command/ListCommandTest.java
Labels: type.Story, priority.High

#50 Add export feature for all transaction data
  build.gradle
  src/main/java/seedu/duke/command/ExportCommand.java
  src/main/java/seedu/duke/csv/Csv.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Story, priority.High

#56 Fixed error in DG for Command
  docs/DeveloperGuide.md
Labels: type.Task

#58 Fix failing test
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
Labels: task.Bug

#64 Method for string representation of TransactionRecurrence
  src/main/java/seedu/duke/classes/TransactionRecurrence.java
Labels: type.Task, priority.Medium

#63 Jason feat export csv
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/ExportCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/csv/CsvReader.java
  src/main/java/seedu/duke/csv/CsvWriter.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#67 Export CSV Feature
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Story, type.Task, priority.High

#68 Update recurring transactions as program runs
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/classes/TransactionRecurrence.java
  src/test/java/seedu/duke/classes/TransactionRecurrenceTest.java
Labels: type.Story, priority.High

#69 Update user guide for export command
  docs/UserGuide.md
Labels: type.Task

#70 Update UG to include recurring transaction option
  docs/UserGuide.md
Labels: type.Task

#75 Update test cases for Help command
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Task, priority.Medium

#77 Refactoring code
  src/main/java/seedu/duke/classes/Expense.java
  src/main/java/seedu/duke/classes/Income.java
  src/main/java/seedu/duke/classes/Transaction.java
  src/main/java/seedu/duke/classes/TransactionRecurrence.java
  src/main/java/seedu/duke/command/AddTransactionCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/classes/TransactionRecurrenceTest.java
Labels: type.Task

#76 Add test cases for Storage, CsvReader, CsvWriter and ExportCommand Class
  TestCSV/Linux/empty/category-store.csv
  TestCSV/Linux/empty/expense-store.csv
  TestCSV/Linux/empty/goal-store.csv
  TestCSV/Linux/empty/income-store.csv
  TestCSV/Linux/error/category-store.csv
  TestCSV/Linux/error/expense-store.csv
  TestCSV/Linux/error/goal-store.csv
  TestCSV/Linux/error/income-store.csv
  TestCSV/Linux/valid/Transactions-all.csv
  TestCSV/Linux/valid/Transactions-in.csv
  TestCSV/Linux/valid/Transactions-out.csv
  TestCSV/Linux/valid/category-store.csv
  TestCSV/Linux/valid/expense-store.csv
  TestCSV/Linux/valid/goal-store.csv
  TestCSV/Linux/valid/income-store.csv
  TestCSV/MacOS/empty/category-store.csv
  TestCSV/MacOS/empty/expense-store.csv
  TestCSV/MacOS/empty/goal-store.csv
  TestCSV/MacOS/empty/income-store.csv
  TestCSV/MacOS/error/category-store.csv
  TestCSV/MacOS/error/expense-store.csv
  TestCSV/MacOS/error/goal-store.csv
  TestCSV/MacOS/error/income-store.csv
  TestCSV/MacOS/valid/Transactions-all.csv
  TestCSV/MacOS/valid/Transactions-in.csv
  TestCSV/MacOS/valid/Transactions-out.csv
  TestCSV/MacOS/valid/category-store.csv
  TestCSV/MacOS/valid/expense-store.csv
  TestCSV/MacOS/valid/goal-store.csv
  TestCSV/MacOS/valid/income-store.csv
  TestCSV/Windows/empty/category-store.csv
  TestCSV/Windows/empty/expense-store.csv
  TestCSV/Windows/empty/goal-store.csv
  TestCSV/Windows/empty/income-store.csv
  TestCSV/Windows/error/category-store.csv
  TestCSV/Windows/error/expense-store.csv
  TestCSV/Windows/error/goal-store.csv
  TestCSV/Windows/error/income-store.csv
  TestCSV/Windows/valid/Transactions-all.csv
  TestCSV/Windows/valid/Transactions-in.csv
  TestCSV/Windows/valid/Transactions-out.csv
  TestCSV/Windows/valid/category-store.csv
  TestCSV/Windows/valid/expense-store.csv
  TestCSV/Windows/valid/goal-store.csv
  TestCSV/Windows/valid/income-store.csv
  build.gradle
  src/main/java/seedu/duke/csv/CsvReader.java
  src/main/java/seedu/duke/csv/CsvWriter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Task, priority.Medium

#78 Add storage class diagram
  docs/DeveloperGuide.md
  docs/images/cs2113-storage-class.png
  docs/uml/storage.puml
Labels: type.Task, priority.Medium

#79 Add diagrams for UI component
  docs/DeveloperGuide.md
  docs/diagrams/ui-class-diagram.puml
  docs/diagrams/ui-sequence-diagram.puml
  docs/images/cs2113-ui-sequence.jpg
  docs/images/cs2113-ui-sequence.png
  docs/images/ui-class-diagram.png
Labels: type.Task

#80 Add list current week/month transactions
  docs/UserGuide.md
  src/main/java/seedu/duke/command/ListCommand.java
  src/test/java/seedu/duke/command/ListCommandTest.java
Labels: type.Task

#82 Update DG to include diagrams
  docs/DeveloperGuide.md
  docs/diagrams/Architecture.puml
  docs/diagrams/ExpenseClassDiagram.puml
  docs/diagrams/IncomeClassDiagram.puml
  docs/diagrams/ParserSequence.puml
  docs/diagrams/Style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ExpenseClassDiagram.png
  docs/images/IncomeClassDiagram.png
  docs/images/ParserSequence.png
Labels: type.Task

#81 Modified ListCommand to print sorted list and include recurrence column
  src/main/java/seedu/duke/classes/StateManager.java
  src/main/java/seedu/duke/command/AddExpenseCommand.java
  src/main/java/seedu/duke/command/AddIncomeCommand.java
  src/main/java/seedu/duke/command/AddTransactionCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveTransactionCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveTransactionCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: priority.Medium
