Repository AY2324S1-CS2113-W12-3/tp, pull requests merged in 2023-11, with the labels that each got.

#87 Fix test cases bugs
  src/main/java/seedu/duke/csv/CsvReader.java
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: task.Bug

#128 Change file location for storage files
  TestCSV/Linux/valid/Transactions-all.csv
  TestCSV/Linux/valid/Transactions-in.csv
  TestCSV/Linux/valid/Transactions-out.csv
  TestCSV/MacOS/valid/Transactions-all.csv
  TestCSV/MacOS/valid/Transactions-in.csv
  TestCSV/MacOS/valid/Transactions-out.csv
  TestCSV/Windows/valid/Transactions-all.csv
  TestCSV/Windows/valid/Transactions-in.csv
  TestCSV/Windows/valid/Transactions-out.csv
  TestCSV/Windows/valid/category-store.csv
  TestCSV/Windows/valid/expense-store.csv
  TestCSV/Windows/valid/goal-store.csv
  TestCSV/Windows/valid/income-store.csv
  src/main/java/seedu/duke/command/ExportCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, task.Bug

#129 Fix parsing of non-negative doubles
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Task

#92 Fix UI diagram issues
  docs/diagrams/ui-class-diagram.puml
  docs/diagrams/ui-sequence-diagram.puml
  docs/images/cs2113-ui-sequence-original.png
  docs/images/cs2113-ui-sequence.png
  docs/images/ui-class-diagram.png
Labels: type.Task

#131 Update UG to clarify valid parameter values and other minor corrections
  docs/UserGuide.md
  docs/diagrams/ui-sequence-diagram.puml
  docs/images/cs2113-ui-sequence-original.png
  docs/images/cs2113-ui-sequence.png
  src/main/java/seedu/duke/classes/TransactionRecurrence.java
  src/main/java/seedu/duke/command/AddTransactionCommand.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
Labels: task.Bug

#134 Modify Parser to detect duplicate arguments and Fix ListCommandTest test cases failing
  docs/UserGuide.md
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/CategoryCommandTest.java
  src/test/java/seedu/duke/command/GoalCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: task.Bug

#133 Fix Storage Bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/classes/Classification.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/ListCommandTest.java
Labels: task.Bug

#136 Fixed error handling for goal and category commands
  src/main/java/seedu/duke/command/CategoryCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: task.Bug

#137 Updating DG
  docs/DeveloperGuide.md
  docs/team/sranay.md
  src/main/java/seedu/duke/command/ExportCommand.java
Labels: type.Task

#135 Add summary command to view total transaction
  docs/UserGuide.md
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: type.Task

#142 Add ability to safely end program using ctrl-c and ctrl-d
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#156 Add edit and summary to help list
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/sranay.md
  src/main/java/seedu/duke/command/HelpCommand.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
Labels: type.Enhancement

#143 Change behaviour of remove goal/category and bugfix list
  TestCSV/Linux/valid/Transactions-all.csv
  TestCSV/Linux/valid/Transactions-in.csv
  TestCSV/Linux/valid/Transactions-out.csv
  TestCSV/Linux/valid/expense-store.csv
  TestCSV/Linux/valid/income-store.csv
  TestCSV/MacOS/valid/Transactions-all.csv
  TestCSV/MacOS/valid/Transactions-in.csv
  TestCSV/MacOS/valid/Transactions-out.csv
  TestCSV/MacOS/valid/expense-store.csv
  TestCSV/MacOS/valid/income-store.csv
  TestCSV/Windows/valid/Transactions-all.csv
  TestCSV/Windows/valid/Transactions-in.csv
  TestCSV/Windows/valid/Transactions-out.csv
  TestCSV/Windows/valid/expense-store.csv
  TestCSV/Windows/valid/income-store.csv
  src/main/java/seedu/duke/classes/StateManager.java
  src/main/java/seedu/duke/classes/TypePrint.java
  src/main/java/seedu/duke/command/AddExpenseCommand.java
  src/main/java/seedu/duke/command/AddIncomeCommand.java
  src/main/java/seedu/duke/command/AddTransactionCommand.java
  src/main/java/seedu/duke/command/CategoryCommand.java
  src/main/java/seedu/duke/command/ClassificationCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/GoalCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveTransactionCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: task.Bug, priority.Medium

#160 Fix storage crashes
  src/main/java/seedu/duke/classes/StateManager.java
  src/main/java/seedu/duke/command/AddExpenseCommand.java
  src/main/java/seedu/duke/command/AddIncomeCommand.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: task.Bug

#157 Fix export bugs
  TestCSV/Linux/valid/Transactions-all.csv
  TestCSV/Linux/valid/Transactions-in.csv
  TestCSV/Linux/valid/Transactions-out.csv
  TestCSV/MacOS/valid/Transactions-all.csv
  TestCSV/MacOS/valid/Transactions-in.csv
  TestCSV/MacOS/valid/Transactions-out.csv
  TestCSV/Windows/valid/Transactions-all.csv
  TestCSV/Windows/valid/Transactions-in.csv
  TestCSV/Windows/valid/Transactions-out.csv
  src/main/java/seedu/duke/command/ExportCommand.java
Labels: task.Bug, priority.Medium

#162 Add various command implementation in DG
  docs/DeveloperGuide.md
Labels: type.Task

#159 Add javadocs
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveTransactionCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Task

#158 Add manual test instructions to DG
  docs/DeveloperGuide.md
Labels: type.Task

#161 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#165 Update help list for list command
  TestCSV/Linux/error/category-store.csv
  TestCSV/Linux/error/goal-store.csv
  TestCSV/MacOS/error/category-store.csv
  TestCSV/MacOS/error/goal-store.csv
  TestCSV/Windows/error/category-store.csv
  TestCSV/Windows/error/goal-store.csv
  docs/team/sranay.md
  src/main/java/seedu/duke/command/ExportCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/ExportCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Enhancement

#172 Add javadocs for storage and help command
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Task

#167 Modify EditTransactionCommand to allow multiple arguments changes
  src/main/java/seedu/duke/command/EditTransactionCommand.java
  src/test/java/seedu/duke/command/EditTransactionCommandTest.java
Labels: type.Enhancement

#177 Fix edge case for edit with uncategorised classifications
  src/main/java/seedu/duke/command/EditTransactionCommand.java
Labels: task.Bug

#179 Edit message for SummaryCommand
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/test/java/seedu/duke/command/SummaryCommandTest.java
Labels: type.Enhancement

#166 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/ListSequenceDiagram.png
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ui-class-diagramv2.png
  docs/diagrams/ui-class-diagramv2.puml
  docs/images/ListSequenceDiagram.png
  docs/images/ui-class-diagramv2.png
Labels: type.Task
